### ISSUE TITLE
Installing instructions error on repository url

### ISSUE THREAD

**Issue by cautbur** [charlesparvin/KCFinderBundle#1]
On README.md, On install instructions, Github url to add to our composer.json is bad written, when I have triyed to install the bundle, composer give me an error, it's because you have to add ".git" to the end. This should be:
```
"repositories": [
    {
        "type": "git",
            "url": "https://github.com/jocelynkerbourch/KCFinderBundle.git"
    }
],
```
Thanks and best regards.

**Comment by charlesparvin** [comment]
Thanks, accepted your pull request that fixed it
